<?php

// classmap_psr4_lower.php @generated by Shift CMS
// Composer event: post-autoload-dump

$baseDir = dirname(dirname(__DIR__));

return [
    'psr4lower' => [
        'shift\\system\\core\\autoload\\classloader' => $baseDir . '/core/autoload/classloader.php',
        'shift\\system\\core\\autoload\\psr4lower' => $baseDir . '/core/autoload/psr4lower.php',
        'shift\\system\\core\\bags' => $baseDir . '/core/bags.php',
        'shift\\system\\framework' => $baseDir . '/framework.php',
        'shift\\system\\core\\config' => $baseDir . '/core/config.php',
    ],
];
