<?php

// classmap_psr4_lower.php @generated by Shift CMS
// Composer event: post-autoload-dump

$baseDir = dirname(dirname(dirname(__DIR__)));

return [
    'psr4lower' => [
        'shift\\site\\controller\\startup\\startup' => $baseDir . '/site/controller/startup/startup.php',
        'shift\\system\\core\\autoload\\classloader' => $baseDir . '/system/core/autoload/classloader.php',
        'shift\\system\\core\\autoload\\psr4lower' => $baseDir . '/system/core/autoload/psr4lower.php',
        'shift\\system\\core\\bags' => $baseDir . '/system/core/bags.php',
        'shift\\system\\core\\database' => $baseDir . '/system/core/database.php',
        'shift\\system\\core\\http\\request' => $baseDir . '/system/core/http/request.php',
        'shift\\system\\core\\http\\response' => $baseDir . '/system/core/http/response.php',
        'shift\\system\\core\\logger' => $baseDir . '/system/core/logger.php',
        'shift\\system\\core\\mvc\\controller' => $baseDir . '/system/core/mvc/controller.php',
        'shift\\system\\core\\registry' => $baseDir . '/system/core/registry.php',
        'shift\\system\\core\\session' => $baseDir . '/system/core/session.php',
        'shift\\system\\framework' => $baseDir . '/system/framework.php',
        'shift\\system\\helper\\arr' => $baseDir . '/system/helper/arr.php',
        'shift\\system\\core\\config' => $baseDir . '/system/core/config.php',
    ],
];
