<?php

// classmap_psr4_lower.php @generated by Shift
// Composer event: post-autoload-dump

$baseDir = dirname(dirname(__DIR__));

return [
    'psr4lower' => [
        'shift\\system\\framework\\autoload\\classloader' => $baseDir . '/framework/autoload/classloader.php',
        'shift\\system\\framework\\autoload\\psr4lower' => $baseDir . '/framework/autoload/psr4lower.php',
        'shift\\system\\kernel' => $baseDir . '/kernel.php',
    ],
];
